### ISSUE TITLE
Determine best format for the AOT runtime image

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/dart-docker#3]
Currently the runtime image assumes that you compile your server app to a [Dart exe](https://dart.dev/tools/dart-compile#exe). 

Should we consider copying in https://dart.dev/tools/dartaotruntime to the image, and then serve the app from even smaller [AOT snapshots](https://dart.dev/tools/dart-compile#aot-snapshot) rather than a full exe?

**Comment by mit-mit** [comment]
Thoughts @jonasfj @subfuzion @kevmoo ?

**Comment by subfuzion** [comment]
When I created subfuzion/dart:slim, I did test both ways before deciding to settle on creating an exe. Ultimately all the bits you need, whether as one file or two, have to get copied to the final image anyway. Although I used [subfuzion/dart:slim](https://github.com/subfuzion/dart-docker-slim/blob/main/Dockerfile#L3-L21) (essentially an image from scratch plus essential system libs and conf files) for the Dart Functions Framework ([example](https://github.com/GoogleCloudPlatform/functions-framework-dart/blob/main/examples/hello/Dockerfile#L14-L15)), the same idea applies here, as shown in this [example](https://github.com/dart-lang/dart-docker/blob/main/examples/Dockerfile.scratch-functions-framework#L15-L16).

So perhaps it's just splitting hairs in terms of performance, but it still seems like it's better for even the tiniest of efficiencies that you're loading a [single file](https://github.com/dart-lang/dart-docker/blob/main/examples/Dockerfile.scratch-functions-framework#L19) into memory and executing it rather than two. Maybe we should ask @mraleph for an opinion?

**Comment by mraleph** [comment]
I think it is probably almost the same thing in terms of performance right now this "exe" thing is just an AOT snapshot literally glued to the end of the AOT runtime.

**Comment by mit-mit** [comment]
From some basic experiments on macOS, using AOT snapshots would make the app part 6 MB smaller. Does that matter at all for Docker startup perf @subfuzion?

```
mit-macbookpro4:tmp mit$ ll hello*
-rw-r--r--  1 mit  primarygroup   991424 Apr 26 14:55 hello.aot
-rwxr-xr-x  1 mit  primarygroup  7348432 Apr 26 14:55 hello.exe
```

**Comment by subfuzion** [comment]
TBH, I don't know how this would matter unless there is some other performance advantage. The final bits for the image `FROM scratch` will need to ensure it contains *both* `dartaotruntime` *and* the exe instead of just the exe. It's not clear to me how this is a benefit or how this is also clearer to end users who may or may not need to update the `CMD` (or `ENTRYPOINT`) instruction.
